### ISSUE TITLE
Locally served application crashes after initial page load

### ISSUE THREAD

**Issue by EmergentBehavior** [watson-developer-cloud/dialog-tool#11]
```
My-Rig:dialog-tool josh$ node app.js
listening at: 3000
[PATH_TO_APP]/dev/dialog-tool/node_modules/request/request.js:963
  self.req = self.httpModule.request(reqOptions)
                            ^

TypeError: Cannot read property 'request' of undefined
    at Request.start ([PATH_TO_APP]/dev/dialog-tool/node_modules/request/request.js:963:29)
    at Request.end ([PATH_TO_APP]/dev/dialog-tool/node_modules/request/request.js:1531:10)
    at IncomingMessage.onend (_stream_readable.js:490:10)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by germanattanasio** [comment]
In `app.js`, replace the `username`, `password` and `url`.
The problem is that you are doing a request to `<url>`:yum:

**Comment by germanattanasio** [comment]
I've updated the app with the `url` value since it doesn't change but you will still need to replace `username` and `password`

**Comment by EmergentBehavior** [comment]
Cool, thanks for clarification.
