### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/dialog-tool#50]
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/felipe/dialog-tool/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/felipe/dialog-tool/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/home/felipe/dialog-tool/node_modules/express/lib/response.js:249:15)
    at /home/felipe/dialog-tool/config/error-handler.js:34:28
    at Layer.handle_error (/home/felipe/dialog-tool/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/felipe/dialog-tool/node_modules/express/lib/router/index.js:310:13)
    at /home/felipe/dialog-tool/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/felipe/dialog-tool/node_modules/express/lib/router/index.js:330:12)
    at next (/home/felipe/dialog-tool/node_modules/express/lib/router/index.js:271:10)
```

**Comment by germanattanasio** [comment]
@johnfelipe when did you fork the code? did you update the credentials to run it locally?

**Comment by johnfelipe** [comment]
yes sure, but that error show me in command prompt

**Comment by germanattanasio** [comment]
I never saw that error before :(

**Comment by azizj1** [comment]
I'm getting the same error when run locally. Happens whenever I go to localhost:3000 and when I use the "Have Conversation" tool. I forked it yesterday and I updated the credentials in app.js to run it locally. 

Any help would be appreciated.

**Comment by michaelchien1972** [comment]
This can be reproduced by following
1. https://bluemix.net/deploy?repository=https://github.com/watson-developer-cloud/dialog-nodejs
2. Deploy to Bluemix
3. Launch application
4. Set any complete dialog xml to upload
5. error message on web: Error creating the dialogs.
6. error message from blue mix console:

2016-08-05T21:01:24.190+0800
[App/0]
err
at ServerResponse.json (/home/vcap/app/node_modules/express/lib/response.js:250:15)
2016-08-05T21:01:24.190+0800
[App/0]
err
at trim_prefix (/home/vcap/app/node_modules/express/lib/router/index.js:310:13)
2016-08-05T21:01:24.190+0800
[App/0]
err
at ServerResponse.send (/home/vcap/app/node_modules/express/lib/response.js:164:12)
2016-08-05T21:01:24.190+0800
[App/0]
err
at Function.process_params (/home/vcap/app/node_modules/express/lib/router/index.js:330:12)
2016-08-05T21:01:24.190+0800
[App/0]
err
at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
2016-08-05T21:01:24.190+0800
[App/0]
err
at ServerResponse.header (/home/vcap/app/node_modules/express/lib/response.js:719:10)
2016-08-05T21:01:24.190+0800
[App/0]
err
at Layer.handle_error (/home/vcap/app/node_modules/express/lib/router/layer.js:71:5)
2016-08-05T21:01:24.190+0800
[App/0]
err
at /home/vcap/app/node_modules/express/lib/router/index.js:280:7
2016-08-05T21:01:24.190+0800
[App/0]
err
Error: Can't set headers after they are sent.
2016-08-05T21:01:24.190+0800
[App/0]
err
at /home/vcap/app/config/error-handler.js:34:28
2016-08-05T21:01:24.190+0800
[App/0]
err
at next (/home/vcap/app/node_modules/express/lib/router/index.js:271:10)

Please fix it asap. Thank you.
